### ISSUE TITLE
Feature request: Asset handling

### ISSUE THREAD

**Issue by timofei-iatsenko** [timofei-iatsenko/keycloakify-emails#9]
It's not clear how to handle assets if they are served from keycloak instance. 

I believe that the best way would be to store them somewhere outside of the keycloak for example in s3 bucket, but it's not always possible, so the library should provide a way to store images in the keycloak instance itself.

I'm going to prepare an infra for that and documentation. 

Keycloak documentation: https://www.keycloak.org/docs/latest/server_development/?utm_source=chatgpt.com#adding-an-image-to-an-email-theme

**Comment by DmitriiSolovev** [comment]
Hi @timofei-iatsenko !

I discovered an issue with displaying SVG background images in email templates. When building the email theme, SVG assets from `/emails/templates/assets/` are not being copied to the final theme's directory structure in `dist_keycloak/theme/my-theme/email/`.

This causes the background images defined in `layout.tsx` to fail loading in email templates, since Keycloak can't find the referenced assets.

Current code in `layout.tsx`:
```tsx
export const EmailLayout = ({
    locale,
    children,
    preview
}: PropsWithChildren<{ preview: ReactNode; locale: string }>) => {
    return (
        <Html lang={locale}>
            <Head />
            <Preview>{preview}</Preview>
            <Body style={main}>
                <Container style={container}>
                    <Background src="./templates/assets/big-diamond-500x500.svg" style={background}>
                        <Section style={box}>
                            <div style={box2}>{children}</div>
                        </Section>
                    </Background>
                </Container>
            </Body>
        </Html>
    );
};
```

Potential workarounds that could help:

1. Add a post-build step that copies assets to the email theme directory
2. Convert SVG to Data URL and embed it directly in the template styles
3. Add support for copying assets in keycloakify-emails build process

Would any of these approaches make sense to implement? Happy to help test potential solutions.

Let me know if you need any additional details about the issue.

Current keycloakify-emails version: 2.0.2

P.S. I inspected the built theme JAR and confirmed assets are not included in the final theme structure.

<img width="536" alt="image" src="https://github.com/user-attachments/assets/e638ee7f-d855-4211-9cfb-4448734ff508" />
<img width="489" alt="image" src="https://github.com/user-attachments/assets/8eb32c43-3ce9-4dd4-9da2-27a13bbd7488" />
<img width="466" alt="image" src="https://github.com/user-attachments/assets/e19fa33c-dab0-472b-992a-aa74cbcbbc9b" />

**Comment by timofei-iatsenko** [comment]
Thanks for your comment. This functionality is not implemented yet. I'm going to work on that today and next week. 

BTW i don't recommend you to use SVG in the emails, the clients support is very little
https://www.caniemail.com/features/html-svg/
https://www.caniemail.com/features/image-svg/
